template_dir_name: static/templates
ade_dir_name: /usr/local/french_thesaurus_builders/ADE/
commune:
    shp: COMMUNE.shp
    fields:
      nom: NOM_COM
      code: INSEE_COM
      nomdept: NOM_DEP
      codedept: INSEE_DEP
    template: CommunesFR.xml
departement:
    shp: DEPARTEMENT.shp
    fields:
      nom: NOM_DEP
      code: INSEE_DEP
      codereg: INSEE_REG
    template: DepartementFR.xml
region:
    shp: REGION.shp
    fields:
      nom: NOM_REG
      code: INSEE_REG
    template: RegionFR.xml
epci:
    shp: EPCI.shp
    fields:
      nom: NOM_EPCI
      code: CODE_EPCI
    template: EpciFR.xml